spring.application.name=Microservice 1
server.port=8081

# In docker network, target is the container name ms2-service
ms2.service.base-url=http://ms2-service:8082/

oauth2.client-id=legacy-app
oauth2.client-secret=cm-secret-123

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

logging.level.com.demo.docker=INFO
logging.level.org.springframework.web.client=DEBUG
